version: "3"
services:
  users-node:
    container_name: users-node
    restart: always
    build:
      context: ./packages/users-node
      args:
        NODE_ENV: development
    command: npm run dev
    environment:
      - PORT=${NODE_PORT}
      - MONGO=${USERS_MONGO_NAME}:${MONGO_PORT}
    ports:
      - "3001:${NODE_PORT}"
    volumes:
      - ./packages/users-node:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - ${USERS_MONGO_NAME}
    depends_on:
      - ${USERS_MONGO_NAME}
  users-mongo:
    container_name: ${USERS_MONGO_NAME}
    image: mongo
    volumes:
      - users-mongo:/data/db
    ports:
      - 27017:27017

  car-points-node:
    container_name: car-points-node
    restart: always
    build: ./packages/car-points-node
    environment:
      - PORT=3000
      - MONGO=car-points-mongo:${MONGO_PORT}
    ports:
      - 3002:3000
    volumes:
      - ./packages/car-points-node:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - car-points-mongo
    depends_on:
      - car-points-mongo

  car-points-mongo:
    container_name: car-points-mongo
    image: mongo
    volumes:
      - car-points-mongo:/data/db
    ports:
      - 27018:27017

  personal-data-server:
    container_name: personal-data-server
    restart: always
    build:
      context: ./packages/personal-data-server
      args:
        NODE_ENV: development
    command: npm run dev
    environment:
      - PORT=${NODE_PORT}
      - AUTH_SERVICE=http://${USERS_NODE_NAME}:${NODE_PORT}
    ports:
      - "3003:${NODE_PORT}"
    volumes:
      - ./packages/personal-data-server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - users-node

volumes:
  users-mongo:
  car-points-mongo: