version: "2.4"
services:
  users-node:
    container_name: users-node
    restart: always
    build:
      context: ./packages/users-node
      args:
        NODE_ENV: development
    command: npm run dev
    environment:
      - PORT=${NODE_PORT}
      - MONGO=${USERS_MONGO_NAME}:${MONGO_PORT}
    ports:
      - "3001:${NODE_PORT}"
    volumes:
      - ./packages/users-node:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - ${USERS_MONGO_NAME}
    depends_on:
      - ${USERS_MONGO_NAME}
  users-mongo:
    container_name: ${USERS_MONGO_NAME}
    image: mongo
    volumes:
      - users-mongo:/data/db
    ports:
      - 27019:27017

  car-points-node:
    container_name: car-points-node
    restart: always
    build: ./packages/car-points-node
    environment:
      - PORT=3000
      - MONGO=car-points-mongo:${MONGO_PORT}
    ports:
      - 3002:3000
    volumes:
      - ./packages/car-points-node:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - car-points-mongo
    depends_on:
      - car-points-mongo

  car-points-mongo:
    container_name: car-points-mongo
    image: mongo
    volumes:
      - car-points-mongo:/data/db
    ports:
      - 27018:27017

  personal-data-db:
    container_name: personal-data-db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - personal-data-db:/data/db

  personal-data-service:
    container_name: ${PERSONAL_DATA_SERVICE}
    restart: always
    build:
      context: ./packages/personal-data-service
    command: npm run dev
    environment: 
      - PORT=${NODE_PORT}
      - MONGO=personal-data-db
    ports:
      - 3005:${NODE_PORT}
    volumes:
      - ./packages/personal-data-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - personal-data-db

  personal-data-server:
    container_name: ${PERSONAL_DATA_SERVER}
    restart: always
    build:
      context: ./packages/personal-data-server
      args:
        NODE_ENV: development
    command: npm run dev
    environment:
      - PORT=${NODE_PORT}
      - AUTH_SERVICE=http://${USERS_NODE_NAME}:${NODE_PORT}
      - PERSONAL_DATA_SERVICE=http://${PERSONAL_DATA_SERVICE}:${NODE_PORT}
    ports:
      - "3003:${NODE_PORT}"
    volumes:
      - ./packages/personal-data-server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - users-node
      - personal-data-service

  personal-data-client:
    container_name: ${PERSONAL_DATA_CLIENT}
    restart: always
    build:
      context: ./packages/personal-data-client
    command: npm run dev
    environment:
      - PORT=3004
      - SERVER=http://${PERSONAL_DATA_SERVER}:${NODE_PORT}
    ports:
      - "3004:3004"
    volumes:
      - ./packages/personal-data-client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - ${PERSONAL_DATA_SERVER}

volumes:
  users-mongo:
  car-points-mongo:
  personal-data-db: