version: "2"
services:
  users-node:
    container_name: users-node
    restart: always
    build: ./packages/users-node
    environment:
      - PORT=3000
      - MONGO=${USERS_MONGO_NAME}:${USERS_MONGO_PORT}
    ports:
      - "3001:3000"
    volumes:
      - ./packages/users-node:/usr/src/app
    links:
      - ${USERS_MONGO_NAME}
    depends_on:
      - ${USERS_MONGO_NAME}
  users-mongo:
    container_name: ${USERS_MONGO_NAME}
    image: mongo
    volumes:
      - users-mongo:/data/db
volumes:
  users-mongo:
