version: "2"
services:
  node:
    container_name: node
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server:/usr/src/app
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data:
